# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('src', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
