# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='src',
            new_name='photo',
        ),
    ]
